// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prefabsoft.money;

import com.prefabsoft.money.ItemTag;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ItemTag_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ItemTag.entityManager;
    
    public static final EntityManager ItemTag.entityManager() {
        EntityManager em = new ItemTag().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ItemTag.countItemTags() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ItemTag o", Long.class).getSingleResult();
    }
    
    public static List<ItemTag> ItemTag.findAllItemTags() {
        return entityManager().createQuery("SELECT o FROM ItemTag o", ItemTag.class).getResultList();
    }
    
    public static ItemTag ItemTag.findItemTag(Long id) {
        if (id == null) return null;
        return entityManager().find(ItemTag.class, id);
    }
    
    public static List<ItemTag> ItemTag.findItemTagEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ItemTag o", ItemTag.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ItemTag.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ItemTag.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ItemTag attached = ItemTag.findItemTag(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ItemTag.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ItemTag.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ItemTag ItemTag.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ItemTag merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
