// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prefabsoft.log;

import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

import com.prefabsoft.log.Log;

privileged aspect Log_Roo_Entity {
    
    declare @type: Log: @Entity;
    
    @PersistenceContext
    transient EntityManager Log.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Log.id;
    
    @Version
    @Column(name = "version")
    private Integer Log.version;
    
    public Long Log.getId() {
        return this.id;
    }
    
    public void Log.setId(Long id) {
        this.id = id;
    }
    
    public Integer Log.getVersion() {
        return this.version;
    }
    
    public void Log.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void Log.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Log.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Log attached = Log.findLog(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Log.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public Log Log.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Log merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Log.entityManager() {
        EntityManager em = new Log().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Log.countLogs() {
        return entityManager().createQuery("select count(o) from Log o", Long.class).getSingleResult();
    }
    
    public static List<Log> Log.findAllLogs() {
        return entityManager().createQuery("select o from Log o", Log.class).getResultList();
    }
    
    public static Log Log.findLog(Long id) {
        if (id == null) return null;
        return entityManager().find(Log.class, id);
    }
    
    public static List<Log> Log.findLogEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("select o from Log o", Log.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
