// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prefabsoft.log;

import com.prefabsoft.log.Log;
import java.util.Date;

privileged aspect Log_Roo_JavaBean {
    
    public String Log.getLogLevel() {
        return this.logLevel;
    }
    
    public void Log.setLogLevel(String logLevel) {
        this.logLevel = logLevel;
    }
    
    public String Log.getLogMessage() {
        return this.logMessage;
    }
    
    public void Log.setLogMessage(String logMessage) {
        this.logMessage = logMessage;
    }
    
    public Boolean Log.getActive() {
        return this.active;
    }
    
    public void Log.setActive(Boolean active) {
        this.active = active;
    }
    
    public Date Log.getCreateDate() {
        return this.createDate;
    }
    
    public void Log.setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    public Date Log.getUpdateDate() {
        return this.updateDate;
    }
    
    public void Log.setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
}
