// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prefabsoft.web;

import com.prefabsoft.money.ItemTag;
import com.prefabsoft.web.ItemTagController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ItemTagController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ItemTagController.create(@Valid ItemTag itemTag, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, itemTag);
            return "itemtags/create";
        }
        uiModel.asMap().clear();
        itemTag.persist();
        return "redirect:/itemtags/" + encodeUrlPathSegment(itemTag.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ItemTagController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ItemTag());
        return "itemtags/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ItemTagController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("itemtag", ItemTag.findItemTag(id));
        uiModel.addAttribute("itemId", id);
        return "itemtags/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ItemTagController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("itemtags", ItemTag.findItemTagEntries(firstResult, sizeNo));
            float nrOfPages = (float) ItemTag.countItemTags() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("itemtags", ItemTag.findAllItemTags());
        }
        return "itemtags/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ItemTagController.update(@Valid ItemTag itemTag, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, itemTag);
            return "itemtags/update";
        }
        uiModel.asMap().clear();
        itemTag.merge();
        return "redirect:/itemtags/" + encodeUrlPathSegment(itemTag.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ItemTagController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, ItemTag.findItemTag(id));
        return "itemtags/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ItemTagController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ItemTag itemTag = ItemTag.findItemTag(id);
        itemTag.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/itemtags";
    }
    
    void ItemTagController.populateEditForm(Model uiModel, ItemTag itemTag) {
        uiModel.addAttribute("itemTag", itemTag);
    }
    
    String ItemTagController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
